

services:
  monitor:
    image: attestation-suite
    network_mode: host
    volumes:
      - ../credentials.prepared/monitor:/app/attestation-suite-config
      - ../../../stats:/app/stats
    container_name: monitor
    command: monitor
    restart: unless-stopped